apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-cert-exporter
  namespace: k8s-cert-exporter
  labels:
    app.kubernetes.io/name: prometheus-k8s-cert-exporter
    app.kubernetes.io/component: exporter
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: prometheus-k8s-cert-exporter

  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP